### ISSUE TITLE
Can't Activate Quizmaster Migrate Plugin even after activating quizmaster plugin

### ISSUE THREAD

**Issue by skaejaz** [goldhat/quizmaster#134] opened 2017-06-08 09:21 UTC
Hi, 

I'm Getting these error after trying to activate quiz master migrate plugin
QuizMaster Migrate requires QuizMaster!

**Comment by goldhat** [comment] 2017-06-08 16:33
Is your main plugin directory named "quizmaster"? Sometimes if you're using the zip from GitHub it will have an extra version number attached to the main directory, which doesn't happen if the plugin is installed from Wordpress.org. The activation check is looking for the plugin being active at /plugins/quizmaster/quizmaster.php.

**Comment by goldhat** [comment] 2017-06-08 17:13
I just tested this issue on a new demo site, with quizmaster installed and quizmaster-migrate activated normally. Cannot reproduce this issue, hopefully it's caused by main quizmaster directory being improperly named?

**Comment by goldhat** [comment] 2017-08-26 21:49
Closing, this is a commonly reported issue but easy to fix by ensuring "fieldmaster" main directory is "/fieldmaster/".

**Closed by goldhat** 2017-08-26 21:49 UTC
