### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by larnoult** [goldhat/quizmaster#141] opened 2017-08-02 16:19 UTC
Hey!
Great plugin!
Long time user of WP-pro-quizz, I recently switched because its leaderboard is unfortunately not working anymore, and I read you would develop such extension. 
I'm working for a french educ-Tech NGO; children and teachers are meant to use your plugin to design and/or solve enigmas. 
So I need french translation up and running :-) 
I followed [your step ](https://github.com/goldhat/quizmaster/wiki/Translating-QuizMaster) and I'd be happy to share with you the french nearly complete translation. 
Problem is .. it doesn't work :( 
First off, I think there is a typo in your instructions; you wrote:

> Save PO file - with the name "wp-pro-qioz-de_DE.po"

I guess you either meant wp-pro-quiz-de_DE.po or more likely quizmaster-de_DE.po.. Anyway I tried the three names, without luck. 
Any idea? Am I the only one struggling with translation here? 

Thanks for your help!

Best,

**Comment by goldhat** [comment] 2017-08-08 06:55
The correct name would likely be quizmaster-de-DE.po, however we've done no testing of translation support thus far it's just not been possible to get to that. We'll definitely need to update the strings in the .pot file because many have changed. Presuming that translations worked in WP Pro Quiz (I believe they did) then the steps should be the same, but perhaps something in the build broke that support.

**Comment by goldhat** [comment] 2017-08-08 07:04
For reference: https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/

Note that .mo and .po files are required, naming convention should be "quizmaster-de_DE.mo" and "quizmaster-de_DE.po" for example.

**Comment by goldhat** [comment] 2017-08-15 01:59
Main problem regarding translation appears to be that the .pot file is outdated, and further that some of the strings with variables are not properly handled using functions such as sprintf() therefore when we generate the .pot file, translation .mo files made from it tend to be corrupted. We're working on proper handling of the strings that contain variables, tests with those string omitted work fine. 

We expect to have this resolved in a few days, and will release it in a v0.6.5, and when it is confirmed that it works for translation we'll do a full release of v0.7.0 as translation-ready.

**Comment by goldhat** [comment] 2017-08-15 04:00
v0.6.5 released with updated .pot file at /languages/quizmaster.pot, download at https://github.com/goldhat/quizmaster/releases/tag/0.6.5 or update from WP directory. 

Translation files should be named according to WP convention "[text-domain]-[language-code].mo", example for French: "quizmaster-fr_FR.mo". 

The translation should be provided as both .po and .mo file, the .mo file is the only one actually used for translations.

**Comment by goldhat** [comment] 2017-08-26 21:59
Confirmed translation-ready in WP support post, as of v0.7+

**Closed by goldhat** 2017-08-26 21:59 UTC
Labels: backend, debugging
