### ISSUE TITLE
Shortcode to Display quiz is not working

### ISSUE THREAD

**Issue by skaejaz** [goldhat/quizmaster#135] opened 2017-06-08 09:25 UTC
Hi,

I have added shortcode to display quiz [QuizMaster 17] where 17 is my quiz id but it is not working.
and also i have tried to preview quiz directly i'm getting "page not found error"

**Comment by goldhat** [comment] 2017-06-08 16:36
I'll run a retest later today on the quizmaster shortcode, for now try these 2 things:

1. Visit your WP settings page "permalinks" (and resave the permalink settings to refresh) and then revisit the quiz "single page". Let me know if that fixes the single view page.

2. In the shortcode make it [quizmaster id=17].

Let me know if either or both of these steps fix the shortcode display.

**Comment by goldhat** [comment] 2017-06-08 17:30
These issue was reproduced (argument handling was not capturing the id passed in shortcode) and we've tested a fix for that, either [quizmaster id="1"] or [quizmaster 1] will work where you have a quiz with ID 1. However I'd suggest use the full [quizmaster id="1"] because support for [quizmaster 1] may be dropped in later versions if there are more arguments available such as overriding quiz settings. 

For the issue with the single page views, we needed to flush the permalinks, you can do that manually but the latest version has the fix on activation of the plugin. 

Both fixes will be in next release here on GitHub, 0.6.4 (or higher). In the meantime those fixes are in the current master repo. We're working on one other critical bug before making an official release.

**Comment by goldhat** [comment] 2017-08-26 21:58
This should be resolved as of v0.7+ releases, closing ticket.

**Closed by goldhat** 2017-08-26 21:58 UTC
